### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "e6f913cdaae6464db10f93e960fbab20",
  "accountNumber": "1000000002",
  "amount": 12345
}

### query transaction
GET http://localhost:8080/transaction/e7594910494040a9be5916ff0e3a0fff